@authToken = {{login.response.body.$.access_token}}
@authTokenNormal = {{loginNormal.response.body.$.access_token}}
@rootPassword = {{$processEnv MFE_ROOT_PASSWORD}}


### LOGIN
# @name login
POST http://localhost:8080/api/oauth2/token
Content-Type: application/json

{
    "client_id": "root@local",
    "client_secret": "{{rootPassword}}"
}

### LOGIN normal user
# @name loginNormal
POST http://localhost:8080/api/oauth2/token
Content-Type: application/json

{
    "client_id": "test@local",
    "client_secret": "test123"
}


### CREATE ResourceGroup
POST http://localhost:8080/api/resource-groups
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "tenant": "Fuzz",
    "name": "users"
}